### ISSUE TITLE
Using dependencies should accept array not object (as shown in readme file)

### ISSUE THREAD

**Issue by ryancat** [andywer/threads.js#81] opened 2018-05-10 16:05 UTC
In example given by README.md doesn't work when there are dependencies. 

```
// Run inline code
const jobC = pool.run(
  function(input, done) {
    const hash = md5(input);
    done(hash, input);
  }, {
    // dependencies; resolved using node's require() or the web workers importScript()
    md5 : 'js-md5'
  }
).send('Hash this string!');
```

It seems the run API takes array instead of object as the second argument. I tried to change that but couldn't get this to work easily.

**Comment by andywer** [comment] 2018-05-10 18:16
Yeah, seems like the documentation is flawed. `pool.run()` passes the parameters to `job.run()` to `thread.run()`.

In node there is no second param for `thread.run()`, in the browser it expects the second param of `thread.run()` to be an array, as you said. It will basically just call `importScript()` on those array items.

Needs to be fixed; at least the docs.

**Comment by andywer** [comment] 2019-06-25 21:28
Closing, since the issue is old and there is a completely rewritten v1.0 (beta) now.

**Closed by andywer** 2019-06-25 21:28 UTC
Labels: bug, version 0.x
