### ISSUE TITLE
Option for choosing the worker backend

### ISSUE THREAD

**Issue by aminya** [andywer/threads.js#285] opened 2020-08-01 00:32 UTC
I am running threadsjs inside Atom. The engine itself supports `Webworkers`, `worker_threads`, or `tiny-workers`. I want to experiment with all three backends and see which one is better for my case. Can you add an option to allow doing that?

**Comment by andywer** [comment] 2020-08-01 18:32
Duplicate of #229. Let's keep discussing it there 😉

**Closed by andywer** 2020-08-01 18:32 UTC
