### ISSUE TITLE
cannot build with webpack

### ISSUE THREAD

**Issue by yingjun** [andywer/threads.js#217] opened 2020-02-28 15:30 UTC
I can successfully build without import app-root-path in worker.js. any idea why? thanks

**master.js**
// master.js
```
import { spawn, Thread, Worker } from "threads"

(async () => {
    const auth = await spawn(new Worker("./worker"))
    const hashed = await auth.hashPassword("Super secret password", "1234")
    console.log("Hashed password:", hashed)
    await Thread.terminate(auth)

})()
console.log('master');

```

**worker.js**
```
import appRoot from 'app-root-path';
import sha256 from "js-sha256";
import { expose } from "threads/worker";

expose({
    hashPassword(password, salt) {
        console.log(sha256(password + salt) + appRoot.path);
    }
})
```

**webpack.config.js**

```
const path = require('path')
const webpack = require('webpack')
const nodeExternals = require('webpack-node-externals')
const ThreadsPlugin = require('threads-plugin');

module.exports = {
    entry: {
        server: './master.js',
    },
    output: {
        path: path.join(__dirname, 'dist'),
        publicPath: '/',
        filename: '[name].js'
    },
    plugins: [
        new ThreadsPlugin()
    ],
    target: 'node',

    externals: [nodeExternals()], // Need this to avoid error when working with Express
    module: {
        rules: [
            {
                // Transpiles ES6-8 into ES5
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader"
                }
            }
        ]
    }
}
```

**error stack**
```
 
    ERROR in ./node_modules/app-root-path/lib/resolve.js
    Module not found: Error: Can't resolve 'module' in '/development/threads/node_modules/app-root-path/lib'
     @ ./node_modules/app-root-path/lib/resolve.js 7:18-35
     @ ./node_modules/app-root-path/lib/app-root-path.js
     @ ./node_modules/app-root-path/index.js
     @ ./node_modules/babel-loader/lib!./worker.js
    
    ERROR in ./node_modules/app-root-path/lib/app-root-path.js
    Module not found: Error: Can't resolve 'path' in '/development/threads/node_modules/app-root-path/lib'
     @ ./node_modules/app-root-path/lib/app-root-path.js 4:12-27
     @ ./node_modules/app-root-path/index.js
     @ ./node_modules/babel-loader/lib!./worker.js
    
    ERROR in ./node_modules/app-root-path/lib/resolve.js
    Module not found: Error: Can't resolve 'path' in '/development/threads/node_modules/app-root-path/lib'
     @ ./node_modules/app-root-path/lib/resolve.js 4:11-26
     @ ./node_modules/app-root-path/lib/app-root-path.js
     @ ./node_modules/app-root-path/index.js
     @ ./node_modules/babel-loader/lib!./worker.js
```

**Comment by andywer** [comment] 2020-02-28 15:47
Hey, @yingjun!

Are you sure that `app-root-path` works with webpack? I haven't used it before.

**Comment by yingjun** [comment] 2020-02-29 02:16
Hi, @andywer 
not only app-root-path but also other packages whenever imported in worker.js
also have similar compile errors

**Comment by andywer** [comment] 2020-03-03 08:54
Sorry for the late reply. I think this is probably a duplicate of andywer/threads-plugin#13 – it's due to some quirks of webpack. Not sure how to solve that right now, but also weird that it doesn't happen in all setups (I guess it happens only when using webpack with node.js as target).

Unfortunately I don't have the time right now to debug much deeper.

**Comment by andywer** [comment] 2020-04-06 01:41
@yingjun Sorry that it took so long, but a fix for the issue that I think this might be a duplicate of (see my previous comment) has just been released in threads v1.4.0.

Would you be able to try again and check out the other issue as well?

**Comment by yingjun** [comment] 2020-04-06 03:26
Will do, thanks for your help

Regards,
Yingjun Cui

________________________________

**Comment by andywer** [comment] 2020-05-01 04:16
Any updates, @yingjun?

**Comment by andywer** [comment] 2020-05-16 19:18
Pinging @yingjun

**Comment by andywer** [comment] 2020-05-18 05:10
Should work in latest version of `threads` and `threads-plugin`. Don’t forget to set the `target` in the `threads-plugin`'s options.

**Closed by andywer** 2020-05-18 05:10 UTC
Labels: question
