### ISSUE TITLE
Runtime error: Uncaught TypeError: Object(...) is not a function [vue-cli and Electron Builder]

### ISSUE THREAD

**Issue by markneub** [andywer/threads.js#199] opened 2020-01-10 15:59 UTC
Hi, I'm trying to use threads.js in a project bootstrapped with vue-cli and [Vue CLI Plugin Electron Builder](https://github.com/nklayman/vue-cli-plugin-electron-builder). To start, I'm creating a minimal example:

1. Bootstrap the vue-cli Hello World project with `vue create threadtest`
2. `vue add electron-builder`
3. Configure webpack:
```js
// vue.config.js
const ThreadsPlugin = require("threads-plugin");

module.exports = {
  configureWebpack: {
    externals: {
      "tiny-worker": "tiny-worker"
    },
    plugins: [new ThreadsPlugin()]
  }
};
```
4. Add imports for threads usage (I don't need anything beyond the import to trigger the error)
```js
// src/App.vue
import { spawn, Thread, Worker } from "threads";
```

**The problem:** Webpack compiles the app without issue, but I get a runtime error:

```
Uncaught TypeError: Object(...) is not a function
    at eval (index.js?25f1:6)
    at Module../node_modules/threads/dist-esm/master/index.js (chunk-vendors.js:1411)
    at __webpack_require__ (app.js:786)
    at fn (app.js:151)
    at eval (index.js?833b:1)
    at Module../node_modules/threads/dist-esm/index.js (chunk-vendors.js:1363)
    at __webpack_require__ (app.js:786)
    at fn (app.js:151)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js&:3)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js& (app.js:875)
```

Following stack trace into index.js...
```
// index.js
import { selectWorkerImplementation } from "./implementation";
export { Pool } from "./pool";
export { spawn } from "./spawn";
export { Thread } from "./thread";
/** Worker implementation. Either web worker or a node.js Worker class. */
export const Worker = selectWorkerImplementation(); // error happens on this line: Uncaught TypeError: Object(...) is not a function
```

I've tried all of the suggestions in somewhat-similar looking https://github.com/andywer/threads.js/issues/194 but no luck. Any suggestions?

**Comment by markneub** [comment] 2020-01-11 16:15
After digging around a little more, I see that this error is happening in /master/implementation.js, where `implementation.selectWorkerImplementation` is set.
```js
import * as BrowserImplementation from "./implementation.browser";
import * as NodeImplementation from "./implementation.node";
...
```
`BrowserImplementation` is set, but `NodeImplementation` is not. Removing the `browser` section in package.json fixes this, but then I get the same error mentioned in #194. The problem seems to be something along the lines of Electron behaving as both a browser and a node process. If I just hardcode `runningInNode` to false in /master/implementation.js and /worker/implementation.js, then everything works fine.
```
// const runningInNode = typeof process !== 'undefined' && process.arch !== 'browser' && 'pid' in process;
const runningInNode = false
```
I'm not quite familiar enough with workers or threadsjs to know what the ramifications are, but it seems like one way to fix this is to adjust this `runningInNode` check so it returns false in an electron environment?

**Comment by andywer** [comment] 2020-01-11 17:44
Sorry, I got sick this week. Will look into it soon.

Thanks already for the debugging! I think we can fix it by adding an additional check if the imported `NodeImplementation` is not a valid implementation module.

**Comment by markneub** [comment] 2020-01-12 16:17
Thanks @andywer! One problem I am having now is that I don't seem to be able to use node built-ins in my worker code. I suspect this has more to do with threads-plugin, though, so I've opened an issue over there: https://github.com/andywer/threads-plugin/issues/13.

**Comment by barretron** [comment] 2020-01-14 16:50
@andywer I think the problem is with a combination of the `browser` field in `package.json` and the `implementation.js` file.

Webpack considers the Electron renderer process to be a browser, so it uses the `browser` field, which filters out the `master/implementation.node.js` file.

Then, in `master/implementation.js`, the following line:

```js
const runningInNode = typeof process !== 'undefined' && process.arch !== 'browser' && 'pid' in process
```
Evaluates to `true` in the renderer process, which triggers the load of `master/implementation.node.js`.

And, since it's already been filtered out by webpack, the whole thing errors out.

I was able to work around this with the following snippet in my webpack config (in the plugins section):

```js
    new webpack.NormalModuleReplacementPlugin(
      /\/node_modules\/threads\/dist-esm\/master\/implementation\.js/,
      './implementation.browser.js'
    )
```

is `runningInNode` meant to evaluate to `true` in this case? I'm wondering if `process.arch !== "browser"` was meant to be `process.type === "browser"` (for whatever reason, "browser" is the main process and "renderer" is the renderer process in Electron).

**Comment by bormisov1** [comment] 2020-01-21 10:03
@barretron I was trying to use your workaround, but got `_implementation__WEBPACK_IMPORTED_MODULE_4__.default.isWorkerRuntime is not a function`. Did you have this?

**Comment by bormisov1** [comment] 2020-01-21 11:18
@andywer Yeah, this eliminated the error! Thank you so much for quick response! And also removing webpack plugin config above doesn't get the initial error back, so no need for it.
However, now it fails to load my worker script saying `Uncaught SyntaxError: Unexpected token <` at `worker.ts`, where there's some html, probably the whole vue.js app's index.html. I think that's not related to your library, because I already had this when I was trying to use other worker libs... Maybe you know how to solve it? Thanks again anyway!

**Comment by andywer** [comment] 2020-01-25 10:31
Closing as the issue here seems fixed. Feel free to re-open if I'm wrong.

**Closed by andywer** 2020-01-25 10:31 UTC
Labels: bug
