### ISSUE TITLE
babel-loader and typescript

### ISSUE THREAD

**Issue by yovanoc** [andywer/threads.js#331] opened 2021-01-04 16:54 UTC
Actually I have these configs and it does not work, so can you tell me what I'm doing wrong (of course I have `"module": "ESNext",` in my tsconfig) big thanks

```js
const { join } = require("path");
const { BannerPlugin } = require("webpack");
const ThreadsPlugin = require('threads-plugin');

module.exports = {
  mode: "production",
  devtool: "source-map",
  entry: {
    main: "./src/index.ts"
  },
  output: {
    path: join(__dirname, "lib"),
    filename: "index.js",
    library: "secrecy",
    libraryTarget: "umd"
  },
  target: "web",
  resolve: {
    extensions: [".ts", ".tsx", ".js"],
    fallback: {
      crypto: false,
      path: false
    }
  },
  module: {
    rules: [{ test: /\.tsx?$/, loader: "babel-loader" }]
  },
  plugins: [
    new ThreadsPlugin(),
    new BannerPlugin({
      entryOnly: true,
      raw: true,
      banner: 'typeof window !== "undefined" &&'
    }) // SSR/Node.js guard
  ]
};
```

```json
{
  "presets": [
    "@babel/preset-typescript",
    [
      "@babel/preset-env",
      {
        "loose": true,
        "modules": false,
        "targets": "defaults"
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/proposal-object-rest-spread",
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ]
}
```

**Comment by andywer** [comment] 2021-01-04 17:12
Duplicate of andywer/threads-plugin#34.

**Closed by andywer** 2021-01-04 17:12 UTC
