### ISSUE TITLE
[Question] How to send message from main thread to slave

### ISSUE THREAD

**Issue by WoodySlum** [andywer/threads.js#59] opened 2017-06-07 15:46 UTC
Another question :)
I would like to have a bidirectionnal communication between processes.
For the slave to main direction, `progress` function can be used.
What about the main to slave direction ?

Tried to use `send` method , but it seems to spawn another process id.

Here is a simple use case :
In the slave process, a web server is running (in my case it's a listener on serial port).
At a moment, the main process should update some informations to the web server.
Using send will re-spawn a process, raising a "Port already binded" error.

How to send informations from main process to slave ?

Thanks for helping,

**Comment by andywer** [comment] 2017-06-07 15:59
You can send data to the thread using `spawn.send()`. I guess you do `pool.send()` and that's why it spawns another thread...

It's not quite elegant, but:
- `pool.send()` returns a job
- `job.thread` is the reference to the worker executing the job
- You should be able to do `job.thread.send()`

Am I right about the pool? And why do you need main->slave messaging for a pool job? :)

**Comment by WoodySlum** [comment] 2017-06-07 18:17
Not really, I'm using spawn and run :

        const gObj = {__dirname: __dirname, identifier:identifier, prototype:prototype, data:data, event:"start"};
        const thread  = threads.spawn(function() {})
        .run((input, done, progress) => {
            let counter = 0;
            if (input.event === "start") {
                counter++;
            }

            if (input.event === "other") {
                counter++;
            }
            console.log(counter);
            done(input.identifier);
        })
        .send(gObj)
        .on("progress", function message(tData) {
            if (callback) {
                callback(tData);
            }
        })
        .on("error", function(error) {
            Logger.err("Error in thread");
            Logger.err(error.message);
        })
        .on("done", (identifier) => {
            this.kill(identifier);
            Logger.info("Thread " + identifier + " has been terminated");
        });
        thread.gObj = gObj;

And a little bit later :

            let gObj = this.threads[identifier].gObj;
            gObj.event = "other";
            this.threads[identifier].send(gObj);

When calling the second send, it seems to be executed in a new context.
On console log of the `run` function, it still displays 1.

**Comment by andywer** [comment] 2017-06-07 18:45
Hmm, ok. That should work, but the code snippet is not suitable for re-creating or debugging the issue.

Can you come up with some minimal sample code to reproduce the problem? Right now it's hard to tell if it's really a bug in the library or a bug in the application code. There is also just one `.send()` in your code snippet ;)

**Comment by WoodySlum** [comment] 2017-06-07 19:02
You're welcome 👍 

        const threads = require("threads");
        const thread  = threads.spawn(function() {})
        .run((input, done, progress) => {
            let counter = 0;
            if (input.event === "start") {
                counter++;
            }

            if (input.event === "other") {
                counter++;
            }

            console.log(counter);

            done();
        })
        .send({event:"start"})
        .on("progress", function message(tData) {
            console.log(tData);
        })
        .on("error", function(error) {
            console.log(error.message);
        })
        .on("done", () => {

        });

        // Second send
        thread.send({event:"other"});

**Comment by andywer** [comment] 2017-06-07 19:28
Will have a look into that :)

Btw: Why do you `spawn(function() {}).run(actualLogic)` instead of `spawn(actualLogic)`?

**Comment by WoodySlum** [comment] 2017-06-07 19:29
Good question that's a mistake :) However not better with spawning directly, thanks for helping !

**Comment by WoodySlum** [comment] 2017-06-08 08:26
There is a little mistake in the code, but issue is still there :


        const threads = require("threads");
        const thread  = threads.spawn((input, done, progress) => {
            var counter;
            if (input.event === "start") {
                counter = 0;
                counter++;
            }

            if (input.event === "other") {
                counter++;
            }

            console.log(counter);

            done();
        })
        .send({event:"start"})
        .on("progress", function message(tData) {
            console.log(tData);
        })
        .on("error", function(error) {
            console.log(error.message);
        })
        .on("done", () => {

        });

        // Second send
        thread.send({event:"other"});

What I got :

        1
        NaN

Expected :

        1
        2

**Comment by andywer** [comment] 2017-06-09 10:55
(Sorry, haven't found time to look into this yet. Can hardly make promises when I will right now...)

**Comment by WoodySlum** [comment] 2017-06-09 11:51
No problem @andywer, found a temporary workaround by adding process object to slave context.
Using `this.process.on("message", (data) => {});` works as expected. I do a fork of your project at https://github.com/WoodySlum/threads.js until you can fix the issue :)

**Comment by andywer** [comment] 2017-06-09 13:52
Ahh, I think I know what the problem is:

When you do
```js
spawn((input, done) => {
  let counter = 0
  // ...
})
```

`counter` is in the scope of the `spawn()` parameter function. The function scope that `counter` lives in will be unique to each function call (every `.send()`). For what you want to do `counter` would need to be declared on a higher scope (which is currently not possible) or it must be some kind of global variable (like `process.counter = 0` in your fork).

So it's not exactly a bug, the issue rather is that it's hard to see. Not sure yet how a more elegant solution would need to look like.

**Comment by andywer** [comment] 2017-12-06 20:15
Closing for now, since it seems to be a usability issue that is hardly fixable. Feel free to suggest a documentation update or something alike :)

**Closed by andywer** 2017-12-06 20:15 UTC
Labels: question
