### ISSUE TITLE
Thread Pool has Memory leak Issue

### ISSUE THREAD

**Issue by cashsun** [andywer/threads.js#27] opened 2016-08-17 21:40 UTC
Hi,

I was using the thread pool 0.7 for my company app to handle processing of large array of json objects.
Seems like pool.send(objs) will leave objs inside the job .send returns and stays in memory for quite a long time. I had to call 

`job.once('done', function(stats){` 
       `.......
`
            `delete job.sendArgs; // to mark it for GC`
            `delete job.runArgs;`
            `job.removeAllListeners();`
            `job = null;`
`})`

to prevent the leak. Please use memwatch to measure the memory footprint.

Thanks,

**Comment by andywer** [comment] 2016-08-18 09:06
Hey @cashsun,

thank you! Very good point.
Fixing the Job class should be easy, but I will also need to add memwatch to the unit testing process.

Will let you know when it's fixed 👍

**Comment by andywer** [comment] 2016-08-18 14:11
This should fix it for now: https://github.com/andywer/threads.js/commit/e79a3839ba3399a7772f5b4721b0dcd0f76576bf

Would be nice if you could have a look at it (just in src/) ;)

Still not sure what's the most elegant way to use memwatch (preferably an automatic solution working along the unit tests). Any suggestions?

**Comment by cashsun** [comment] 2016-08-19 17:49
`memwatch.on('leak', function(stats){ console.log('OMG Leak!!')})
`
anywhere executed during run time. It should shout when heap keeps increasing after 5 gc.

Keep pool.send(>1000 objects) for 60s you will see the memory leak log.

**Comment by andywer** [comment] 2016-09-23 07:41
Memory leak is fixed, but will leave it open until I added a test scenario using `memwatch`.

**Comment by DemersM** [comment] 2016-10-24 14:07
I am not sure if it is related, but I have an uncaught exception: out of memory error for a job in a pool that returns json. The pool handle 21 jobs, but only one job throw that error. The json returned by this perticular job is big (8mb), but that's not the biggest json in the pool... The error occurs only in FF, not in Chrome or IE.

I tryed to use the fix e79a383 above but the error occurs anyway.

**Comment by andywer** [comment] 2016-10-24 14:12
Hi @DemersM. Maybe you can provide a small code snippet? But I guess it's not related to the same issue.

**Comment by DemersM** [comment] 2016-10-24 15:17
@andywer Hi! See https://github.com/andywer/threads.js/issues/30

**Comment by andywer** [comment] 2017-03-28 20:19
This issue can be closed, right?

**Comment by cashsun** [comment] 2017-03-28 20:21
Sorry for the delay. No the issue still exists. The cause of the memory leak is due to job has a reference to pool via job.pool which formulates a circular dependency. Make sure when job.on done, job.pool is deleted.

**Comment by DemersM** [comment] 2017-03-29 12:45
simply like this?

```
        .on("done", function(job) {
            console.log(job)
            delete job.pool;
        })
```

**Comment by Bamieh** [comment] 2017-10-27 11:05
deleting the pool from the job eliminates the memory leak? are there anything in the works to solve this?

I love this package but i'm afraid to use it for my project in production due to this issue.

**Comment by andywer** [comment] 2017-12-06 20:19
Not sure if this is still an issue. I know, it's long ago, but has anyone got an update on this?

**Comment by nqkdev** [comment] 2017-12-24 15:27
It is still an issue. I just tried out the threadpool example and took snapshots while sending in message, Job objects never got deleted.

**Comment by tominon** [comment] 2018-05-29 23:15
Any updates on this? I can confirm this is still an issue.

**Comment by andywer** [comment] 2019-08-27 01:45
@joshcorn Wasn't even sure if this is still an issue in v1.0... Drats.

> Is there a way of deleting a job within the pool after it's completed?

No, there is no need to. Jobs are put in a task queue and removed from it when they are dispatched to a worker. The worker in turn has an array of currently running tasks (the running job promise). The promise is removed from this array once the job either succeeds or fails.

Can you provide some small sample code to replicate the issue?

**Comment by andywer** [comment] 2019-08-31 10:29
Cool, that helps a lot, @joshcorn!

First finding: It only seems to happen in node 10 - node 12 seems fine. So I suppose it has to do with the `tiny-worker` polyfill. Still investigating...

**Comment by andywer** [comment] 2019-08-31 14:49
@joshcorn After digging into it further, I think there is no actual issue - it's just that the garbage collector runs asynchronously, so as long as there is still enough memory available it might take a while until the GC runs.

In node 12 it seems to collect the garbage earlier, though.

## Test Setup

I took your example app and ran it with [`ndb`](https://github.com/GoogleChromeLabs/ndb). In node 10 I could see the behavior that you described - the heap kept growing linearly. After taking a heap snapshot, though, it went straight back down and did not increase again on later requests.

Now I added `global.gc(); global.gc(); global.gc();` to the function in `service.js` and ran everything with `npx ndb node --expose-gc ./app.js`. Et voila, now after enforcing immediate GC, the worker's heap size had a super short spike at about 17 MB and immediately (within < 1s) went back to about 9 MB and stayed there, even after additional requests.

PS: I only tested with node 10 and node 12 and all tests have been conducted with `threads@1.0.0-beta.5`.

**Comment by joshcorn** [comment] 2019-09-05 17:09
@andywer Wow, I see that now. If I continue adding jobs (w/ Node 10), eventually the heap does go back down and stays there. Thanks for taking such a deep look at this. I'm glad it wasn't actually an issue.

**Comment by andywer** [comment] 2019-10-01 05:48
Closing as this issue only applies to v0 which has reached its end of life. Please update to v1.0

v1.0 is still in beta as of now, but will be out of beta state very soon and it's already much better than the old v0.

**Closed by andywer** 2019-10-01 05:48 UTC
Labels: version 0.x
